{
 "title": "Plant Data Display",
 "description": "This dashboard is used to display data for the plants. The plant to observe can be set in a textfield",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "selected_plant", "query": "Efeutute" },
   {
    "name": "optimal_temp_min",
    "label": "Optimal min temp",
    "query": {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"optimal_conditions\") \r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\")\r\n  |> filter(fn: (r) => r._field == \"optimal_temp_min\")\r\n  |> last()\r\n  "
    }
   },
   {
    "name": "optimal_temp_max",
    "query": {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"optimal_conditions\") \r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\")\r\n  |> filter(fn: (r) => r._field == \"optimal_temp_max\")\r\n  |> last()\r\n  "
    }
   },
   {
    "name": "optimal_ground_moisture_min",
    "query": {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"optimal_conditions\") \r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\")\r\n  |> filter(fn: (r) => r._field == \"optimal_ground_moisture_min\")\r\n  |> last()\r\n  "
    }
   },
   {
    "name": "optimal_ground_moisture_max",
    "query": {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"optimal_conditions\") \r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\")\r\n  |> filter(fn: (r) => r._field == \"optimal_ground_moisture_max\")\r\n  |> last()\r\n  "
    }
   },
   {
    "name": "optimal_air_moisture_min",
    "query": {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"optimal_conditions\") \r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\")\r\n  |> filter(fn: (r) => r._field == \"optimal_air_moisture_min\")\r\n  |> last()\r\n  "
    }
   },
   {
    "name": "optimal_air_moisture_max",
    "query": {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"optimal_conditions\") \r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\")\r\n  |> filter(fn: (r) => r._field == \"optimal_air_moisture_max\")\r\n  |> last()\r\n  "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Temperature of ${selected_plant}",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1m) // Query the last 5 minutes to keep it efficient\r\n  |> filter(fn: (r) => r._measurement == \"plant_data\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\")\r\n  |> last() // Select only the most recent value"
    }
   ]
  },
  {
   "title": "Temperature Timeline of ${selected_plant}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"plant_data\")\r\n  |> filter(fn: (r) => r._field == \"temperature\") \r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\")"
    }
   ]
  },
  {
   "title": "Ground Moisture of ${selected_plant}",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1m) // Query the last minute to keep it efficient\r\n  |> filter(fn: (r) => r._measurement == \"plant_data\")\r\n  |> filter(fn: (r) => r._field == \"ground_moisture\")\r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\")\r\n  |> last() // Select only the most recent value"
    }
   ]
  },
  {
   "title": "Ground Moisture",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"iot-data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"plant_data\")\r\n  |> filter(fn: (r) => r._field == \"ground_moisture\") \r\n  |> filter(fn: (r) => r.plant_name == \"${selected_plant}\") \r\n"
    }
   ]
  }
 ]
}